github.com:
    users:
        cscott9251:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: cscott9251
